"""fixed review

Revision ID: 30c12dea9306
Revises: ffde01e0a933
Create Date: 2024-06-03 15:42:51.697199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c12dea9306'
down_revision = 'ffde01e0a933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
